### ISSUE TITLE
Add support for Ubuntu 18.04 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [choria-io/packager#1]
It would be nice to have official support for next Ubuntu LTS version, as Puppet already supports it.

I hope it's a good place for this issue. Probably support should be added also to all puppet modules.

**Comment by ripienaar** [comment]
yeah fine to add here, I havnt touched 18.04 but I suspect its systemd and thats about the only place we interact with the OS

could you perhaps confirm that the current choria packages packaged for previous LTS would work on the new LTS when installed?

**Comment by mateusz-gozdek-sociomantic** [comment]
I can confirm, that repo (with `xenial`), package, binaries and services are working on https://app.vagrantup.com/ubuntu/boxes/bionic64.

**Comment by ripienaar** [comment]
excellent news then its quite easy to get us there

**Comment by ripienaar** [comment]
will try to get that going for next release

**Comment by mateusz-gozdek-sociomantic** [comment]
Cool, thanks!

I guess `metadata.json` for modules like https://github.com/choria-io/puppet-choria should also be updated (not sure if anyone cares), as at the moment, even 16.04 is missing :)

**Comment by ripienaar** [comment]
Yeah, in the mean time I put the same deb in a 18.04 repo https://packagecloud.io/choria/release/packages/ubuntu/bionic/choria_0.4.0_amd64.deb

**Comment by ripienaar** [comment]
- [ ] create 18.04 packager
 - [ ] add `build_bionic_64bit_debs` to go-choria circleci
 - [ ] update puppet-choria `metadata.json`
 - [ ] update puppet-mcollective `metadata.json`

That appears to be about it really?

**Comment by ripienaar** [comment]
closing this, next release should be good on 18.04
